### PR TITLE
8316461: Fix: make test outputs TEST SUCCESS after unsuccessful exit

### PR DESCRIPTION
**Pull request by lkorinth**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Error
&nbsp;⚠️ This PR only contains changes already present in the target

### Issue
 * [JDK-8316461](https://bugs.openjdk.org/browse/JDK-8316461): Fix: make test outputs TEST SUCCESS after unsuccessful exit (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/187/head:pull/187` \
`$ git checkout pull/187`

Update a local copy of the PR: \
`$ git checkout pull/187` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/187/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 187`

View PR using the GUI difftool: \
`$ git pr show -t 187`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/187.diff">https://git.openjdk.org/jdk21u/pull/187.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/187#issuecomment-1729481266)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @lkorinth 
do you mind integrating this PR?
Thanks!

**Comment by shipilev** [comment]
Hey @lkorinth, please integrate this or delegate the integration to someone else? Thanks!

**Comment by lkorinth** [comment]
Integrated by Goetz, I missed that I did not need reviews, sorry.

**Pull request closed without merging**
