### PR TITLE
8308609: java/lang/ScopedValue/StressStackOverflow.java fails with "-XX:-VMContinuations"

### PR DESCRIPTION
**Pull request by RealCLanger**
Hi all,

This pull request contains a backport of [JDK-8308609](https://bugs.openjdk.org/browse/JDK-8308609), commit [44a8aa06](https://github.com/openjdk/jdk/commit/44a8aa0691f046d720a789a89c9039a010658f0c) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Andrew Haley on 16 Jun 2023 and was reviewed by Alan Bateman.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8308609](https://bugs.openjdk.org/browse/JDK-8308609): java/lang/ScopedValue/StressStackOverflow.java fails with "-XX:-VMContinuations" (**Bug** - P3)
 * [JDK-8310586](https://bugs.openjdk.org/browse/JDK-8310586): ProblemList java/lang/ScopedValue/StressStackOverflow.java#default with virtual threads on linux-all (**Sub-task** - P3)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [bf6a5604](https://git.openjdk.org/jdk21u/pull/22/files/bf6a5604021a7eb254ae0ca2498a796041570b40)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/22/head:pull/22` \
`$ git checkout pull/22`

Update a local copy of the PR: \
`$ git checkout pull/22` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/22/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22`

View PR using the GUI difftool: \
`$ git pr show -t 22`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/22.diff">https://git.openjdk.org/jdk21u/pull/22.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/22#issuecomment-1655539021)

### CODE REVIEW

**Comment by AlanBateman** [comment]
If this one is integrated then you'll probably need to backport JDK-8311926 too.

**Comment by RealCLanger** [comment]
> If this one is integrated then you'll probably need to backport JDK-8311926 too.

Yes, it's on my list. However, I didn't want to squeeze it in here. I'm currently running tests for this PR.

**Review by MBaesken — APPROVED** [review]

**Comment by AlanBateman** [comment]
> Yes, it's on my list. However, I didn't want to squeeze it in here. I'm currently running tests for this PR.

Okay, I'm mostly wondering about the change to ProblemList-Virtual.txt to exclude it only on linux-x64, it should be all platforms. There is work required to improve the robustness that will surface when this test is run with JTREG_TEST_THREAD_FACTORY=Virtual, it's not specific to linux-x64. I suspect Dan excluded only on that platform because it was only initially seen on that platform.

**Review by AlanBateman — APPROVED** [review]
The backport of JDK-8308609 looks fine.

JDK-8310586 excluded in ProblemList-Virtual.txt for linux-x64 only, it should be generic-all.

**Comment by RealCLanger** [comment]
> JDK-8311926

Yes, this change is done in the follow-up [JDK-8311926](https://bugs.openjdk.org/browse/JDK-8311926). We'll also need [JDK-8310211](https://bugs.openjdk.org/browse/JDK-8310211).

**Comment by RealCLanger** [comment]
GHA failures will be fixed with #36 which I'll integrate as well.

/integrate

**Pull request closed without merging**
