### PR TITLE
8320206: Some intrinsics/stubs missing vzeroupper on x86_64

### PR DESCRIPTION
**Pull request by sviswa7**
---------
### Progress
- [ ] [JDK-8320206](https://bugs.openjdk.org/browse/JDK-8320206) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320206](https://bugs.openjdk.org/browse/JDK-8320206): Some intrinsics/stubs missing vzeroupper on x86_64 (**Enhancement** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/380/head:pull/380` \
`$ git checkout pull/380`

Update a local copy of the PR: \
`$ git checkout pull/380` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/380/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 380`

View PR using the GUI difftool: \
`$ git pr show -t 380`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/380.diff">https://git.openjdk.org/jdk21u/pull/380.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/380#issuecomment-1817120813)

### CODE REVIEW

**Comment by shipilev** [comment]
> /approval

Note the incorrect syntax, so no actual approval request was generated.

**Comment by sviswa7** [comment]
/approval request This is a clean backport and not dependent on any other backport.,
A very small patch with changes to emit missing vzeroupper instructions at select locations to avoid AVX->SSE transition penalties.,
Please approve.

**Comment by jerboaa** [comment]
Please close this PR. OpenJDK 21.0.3 development happens in jdk21u-dev. I.e. this PR needs to move there now.

**Pull request closed without merging**
