### PR TITLE
8317692: jcmd GC.heap_dump performance regression after JDK-8292818

### PR DESCRIPTION
**Pull request by SirYwell**
Hi all,

This pull request contains a backport of commit [8f5f4407](https://github.com/openjdk/jdk/commit/8f5f44070a7c6dbbbd1005f9d0af5ab7c35179df) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Hannes Greule on 19 Oct 2023 and was reviewed by Alex Menkov and Frederic Parain.

Thanks!

---------
### Progress
- [x] [JDK-8317692](https://bugs.openjdk.org/browse/JDK-8317692) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8317692](https://bugs.openjdk.org/browse/JDK-8317692): jcmd GC.heap_dump performance regression after JDK-8292818 (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/274/head:pull/274` \
`$ git checkout pull/274`

Update a local copy of the PR: \
`$ git checkout pull/274` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/274/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 274`

View PR using the GUI difftool: \
`$ git pr show -t 274`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/274.diff">https://git.openjdk.org/jdk21u/pull/274.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/274#issuecomment-1772305031)

### CODE REVIEW

**Comment by SirYwell** [comment]
> Note the test failures. I think we need [bugs.openjdk.org/browse/JDK-8316778](https://bugs.openjdk.org/browse/JDK-8316778) to be in jdk21u before backporting this one.

I see. Thanks for taking care of that!

**Comment by shipilev** [comment]
> I see. Thanks for taking care of that!

No problem. I have just pushed that one to jdk21u, please merge from master here to get the test run:
https://github.com/openjdk/jdk21u/commit/9f0d9ca663b05d2c6003505ab2c5a31d9ad580b6

**Comment by SirYwell** [comment]
Tests passed now, I guess we can proceed.

/integrate

**Pull request closed without merging**
