### PR TITLE
8314191: C2 compilation fails with "bad AD file"

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to fix recent JDK 21 regression.

Additional testing:
 - [x] New test fails without the fix, passes with it
 - [x] Linux AArch64 fastdebug `tier1 tier2 tier3`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8314191](https://bugs.openjdk.org/browse/JDK-8314191) needs maintainer approval

### Issue
 * [JDK-8314191](https://bugs.openjdk.org/browse/JDK-8314191): C2 compilation fails with "bad AD file" (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/190/head:pull/190` \
`$ git checkout pull/190`

Update a local copy of the PR: \
`$ git checkout pull/190` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/190/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 190`

View PR using the GUI difftool: \
`$ git pr show -t 190`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/190.diff">https://git.openjdk.org/jdk21u/pull/190.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/190#issuecomment-1729814995)

### CODE REVIEW

**Comment by shipilev** [comment]
/approval request Fixes a recent C2 regression.

**Comment by shipilev** [comment]
> @shipilev This pull request has been inactive for more than 4 weeks and will be automatically closed if another 4 weeks passes without any activity. To avoid this, simply add a new comment to the pull request. Feel free to ask for assistance if you need help with progressing this pull request towards integration!

Aaaaaachoo! (counts as activity)

**Comment by phohensee** [comment]
The JBS backport request has been approved. :)

**Pull request closed without merging**
