### PR TITLE
8293114: JVM should trim the native heap

### PR DESCRIPTION
**Pull request by shipilev**
Clean backport to get the important feature to LTS users.

Additional testing:
 - [x] Linux AArch64 fastdebug trimming tests
 - [x] Linux AArch64 fastdebug `tier1`
 - [x] Linux AArch64 fastdebug `tier2`
 - [x] Linux AArch64 fastdebug `tier3`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293114](https://bugs.openjdk.org/browse/JDK-8293114): JVM should trim the native heap (**Enhancement** - P4)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/13/head:pull/13` \
`$ git checkout pull/13`

Update a local copy of the PR: \
`$ git checkout pull/13` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/13/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13`

View PR using the GUI difftool: \
`$ git pr show -t 13`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/13.diff">https://git.openjdk.org/jdk21u/pull/13.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/13#issuecomment-1645931458)

### CODE REVIEW

**Comment by dholmes-ora** [comment]
FYI the test is failing for us in mainline [DK-8312525](https://bugs.openjdk.org/browse/JDK-8312525)

**Comment by shipilev** [comment]
> FYI the test is failing for us in mainline [JDK-8312525](https://bugs.openjdk.org/browse/JDK-8312525)

Yup, that one should be resolved by #26.

**Review by tstuefe — APPROVED** [review]
Good + Thanks!

Same as for 17, I would let it steam a bit in 22, if for no other reason than to see if other intermittent issues come up.

**Comment by shipilev** [comment]
Tests are clean. Review is done. Push approval is here.

/integrate

**Pull request closed without merging**
