### PR TITLE
8319104: GtestWrapper crashes with SIGILL in AsyncLogTest::test_asynclog_raw on AIX opt

### PR DESCRIPTION
**Pull request by GoeLin**
Backporting to fix tests for AIX.

Had to remove LogConfiguration:: because [8299825](https://bugs.openjdk.org/browse/JDK-8299825)
Move StdoutLog and StderrLog to LogConfiguration is not in 21.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319104](https://bugs.openjdk.org/browse/JDK-8319104) needs maintainer approval

### Issue
 * [JDK-8319104](https://bugs.openjdk.org/browse/JDK-8319104): GtestWrapper crashes with SIGILL in AsyncLogTest::test_asynclog_raw on AIX opt (**Bug** - P3 - Approved)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)
 * [Joachim Kern](https://openjdk.org/census#jkern) (@JoKern65 - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/350/head:pull/350` \
`$ git checkout pull/350`

Update a local copy of the PR: \
`$ git checkout pull/350` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/350/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 350`

View PR using the GUI difftool: \
`$ git pr show -t 350`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/350.diff">https://git.openjdk.org/jdk21u/pull/350.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/350#issuecomment-1805624657)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
ok

**Review by JoKern65 — APPROVED** [review]
This will backport my jdk PR to jdk21u regarding the differences between jdk and jdk21u in a correct way. LGTM.

**Comment by GoeLin** [comment]
Pre-submit failure: oom in TestAllocHumongousFragment, unrelated.

**Pull request closed without merging**
