### PR TITLE
8322883: [BACKOUT] 8225377: type annotations are not visible to javac plugins across compilation boundaries

### PR DESCRIPTION
**Pull request by raviniitw2012**
javac fails with "Unable to implement <class> method" after fixing [JDK-8225377](https://bugs.openjdk.org/browse/JDK-8225377) and [JDK-8320001](https://bugs.openjdk.org/browse/JDK-8320001) in 21.0.2 . More details in [JDK-8322641](https://bugs.openjdk.org/browse/JDK-8322641).

Backing out fix [JDK-8225377](https://bugs.openjdk.org/browse/JDK-8225377) and [JDK-8320001](https://bugs.openjdk.org/browse/JDK-8320001) from 21.0.2.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8322883](https://bugs.openjdk.org/browse/JDK-8322883) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322883](https://bugs.openjdk.org/browse/JDK-8322883): [BACKOUT] 8225377: type annotations are not visible to javac plugins across compilation boundaries (**Bug** - P3 - Approved)

### Reviewers
 * [Sean Coffey](https://openjdk.org/census#coffeys) (@coffeys - **Reviewer**)
 * [Rob McKenna](https://openjdk.org/census#robm) (@robm-openjdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/427/head:pull/427` \
`$ git checkout pull/427`

Update a local copy of the PR: \
`$ git checkout pull/427` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/427/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 427`

View PR using the GUI difftool: \
`$ git pr show -t 427`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/427.diff">https://git.openjdk.org/jdk21u/pull/427.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/427#issuecomment-1875175513)

### CODE REVIEW

**Review by coffeys — APPROVED** [review]
backout code looks correct

**Review by robm-openjdk — APPROVED** [review]
LGTM

**Pull request closed without merging**
