### PR TITLE
8341059: Change Entrust TLS distrust date to November 12, 2024

### PR DESCRIPTION
**Pull request by GoeLin**
This moves the jdk21u-dev backport by Andrew (https://github.com/openjdk/jdk21u-dev/pull/1015) to jdk21u.
The patch is identical to the one by Andrew.  I.e., the changes to the original version in head are:

"The commit does not apply cleanly to 21u-dev due to the absence of [JDK-8339560](https://bugs.openjdk.org/browse/JDK-8339560). Equivalent changes to those in distrust/Entrust.java are applied to Entrust/Distrust.java instead."

Thanks, Andrew, for preparing the field, here!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8341059](https://bugs.openjdk.org/browse/JDK-8341059) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8341087](https://bugs.openjdk.org/browse/JDK-8341087) to be approved

### Issues
 * [JDK-8341059](https://bugs.openjdk.org/browse/JDK-8341059): Change Entrust TLS distrust date to November 12, 2024 (**Enhancement** - P2 - Approved)
 * [JDK-8341087](https://bugs.openjdk.org/browse/JDK-8341087): Change Entrust TLS distrust date to November 12, 2024 (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/456/head:pull/456` \
`$ git checkout pull/456`

Update a local copy of the PR: \
`$ git checkout pull/456` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/456/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 456`

View PR using the GUI difftool: \
`$ git pr show -t 456`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/456.diff">https://git.openjdk.org/jdk21u/pull/456.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/456#issuecomment-2384909445)

### CODE REVIEW

**Comment by jerboaa** [comment]
https://github.com/openjdk/jdk21u-dev/pull/1015 is in `ready` while this one isn't (should be the other way round now). We'll see if that changes once the bots pick up the updated labels.

**Review by jerboaa — APPROVED** [review]

**Comment by GoeLin** [comment]
Thanks for the approval!

**Comment by gnu-andrew** [comment]
"The patch is identical to the one by Andrew"

Yet, you don't even bother to credit me.

**Comment by GoeLin** [comment]
> "The patch is identical to the one by Andrew"
> 
> Yet, you don't even bother to credit me.

I'm sorry, I meant to by saying "Thanks, Andrew, for preparing the field, here!" Maybe "pave the way" would have been better because your change went clean all the way to 11!

**Pull request closed without merging**
