### PR TITLE
8317039: Enable specifying the JDK used to run jtreg

### PR DESCRIPTION
**Pull request by Shivangi-aa**
This contains the changes of this bug also.
https://bugs.openjdk.org/browse/JDK-8317807

Mach5 testing- https://mach5.us.oracle.com/mdash/jobs/sshivang-jdk21u-20231116-1225-2141342

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317807](https://bugs.openjdk.org/browse/JDK-8317807) needs maintainer approval
- [x] [JDK-8317039](https://bugs.openjdk.org/browse/JDK-8317039) needs maintainer approval

### Issues
 * [JDK-8317039](https://bugs.openjdk.org/browse/JDK-8317039): Enable specifying the JDK used to run jtreg (**Enhancement** - P4 - Approved)
 * [JDK-8317807](https://bugs.openjdk.org/browse/JDK-8317807): JAVA_FLAGS removed from jtreg running in JDK-8317039 (**Bug** - P3 - Approved)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/374/head:pull/374` \
`$ git checkout pull/374`

Update a local copy of the PR: \
`$ git checkout pull/374` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/374/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 374`

View PR using the GUI difftool: \
`$ git pr show -t 374`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/374.diff">https://git.openjdk.org/jdk21u/pull/374.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/374#issuecomment-1814979985)

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Comment by shipilev** [comment]
As a matter of course, please enable GHA testing and trigger it.

**Pull request closed without merging**
