### PR TITLE
8310239: Add missing cross modifying fence in nmethod entry barriers

### PR DESCRIPTION
**Pull request by fisk**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8310239](https://bugs.openjdk.org/browse/JDK-8310239) needs maintainer approval

### Issue
 * [JDK-8310239](https://bugs.openjdk.org/browse/JDK-8310239): Add missing cross modifying fence in nmethod entry barriers (**Bug** - P2 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/359/head:pull/359` \
`$ git checkout pull/359`

Update a local copy of the PR: \
`$ git checkout pull/359` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/359/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 359`

View PR using the GUI difftool: \
`$ git pr show -t 359`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/359.diff">https://git.openjdk.org/jdk21u/pull/359.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/359#issuecomment-1809772417)

### CODE REVIEW

**Comment by shipilev** [comment]
Hey @fisk, do we wait for something here, or can we integrate to 21u? The cutoff for 21.0.2 is soon.

**Comment by fisk** [comment]
> Hey @fisk, do we wait for something here, or can we integrate to 21u? The cutoff for 21.0.2 is soon.

I think I'm waiting for a critical request, but maybe I don't need it?

**Comment by shipilev** [comment]
> I think I'm waiting for a critical request, but maybe I don't need it?

`jdk21u-fix-yes` from maintainer is fine, bots agree and let you integrate. I am not even sure what `CPU21_02-critical-request` on the bug is supposed to mean %)

**Comment by fisk** [comment]
> > I think I'm waiting for a critical request, but maybe I don't need it?
> 
> 
> 
> `jdk21u-fix-yes` from maintainer is fine, bots agree and let you integrate. I am not even sure what `CPU21_02-critical-request` on the bug is supposed to mean %)

Okay, then I will integrate tomorrow.

**Pull request closed without merging**
