### PR TITLE
8313643: Update HarfBuzz to 8.2.2

### PR DESCRIPTION
**Pull request by aivanov-jdk**
This pull request contains a backport of commit [2182c936](https://github.com/openjdk/jdk/commit/2182c93689f35c809f4d79a8002c838f8c4f56f3) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

It updates HarfBuzz to 8.2.2.
The patch applies cleanly.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8319268](https://bugs.openjdk.org/browse/JDK-8319268) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8313643](https://bugs.openjdk.org/browse/JDK-8313643) needs maintainer approval

### Issues
 * [JDK-8313643](https://bugs.openjdk.org/browse/JDK-8313643): Update HarfBuzz to 8.2.2 (**Bug** - P3 - Approved)
 * [JDK-8319268](https://bugs.openjdk.org/browse/JDK-8319268): Build failure with GCC8.3.1 after 8313643 (**Bug** - P4 - Approved)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/336/head:pull/336` \
`$ git checkout pull/336`

Update a local copy of the PR: \
`$ git checkout pull/336` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/336/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 336`

View PR using the GUI difftool: \
`$ git pr show -t 336`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/336.diff">https://git.openjdk.org/jdk21u/pull/336.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/336#issuecomment-1799945881)

### CODE REVIEW

**Comment by prrace** [comment]
> @aivanov-jdk Adding additional issue to issue list: `8319268: Build failure with GCC8.3.1 after 8313643`.

Whilst I guess someone will want this backport anyway, what you wrote about needing it even with GCC 11 but only on 21u is something I can't explain .. I can only guess that some other option difference is also in play in 21u ...

**Review by prrace — APPROVED** [review]

**Review by honkar-jdk — APPROVED** [review]

**Comment by aivanov-jdk** [comment]
> > @aivanov-jdk Adding additional issue to issue list: `8319268: Build failure with GCC8.3.1 after 8313643`.
> 
> Whilst I guess someone will want this backport anyway, what you wrote about needing it even with GCC 11 but only on 21u is something I can't explain .. I can only guess that some other option difference is also in play in 21u ...

I can't explain it either, but I can reproduce it all the time even with local builds. Weird.

**Pull request closed without merging**
