### PR TITLE
Merge jdk21:master

### PR DESCRIPTION
**Pull request by robm-openjdk**
Merge jdk21 into jdk21u

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/14/head:pull/14` \
`$ git checkout pull/14`

Update a local copy of the PR: \
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/14/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14`

View PR using the GUI difftool: \
`$ git pr show -t 14`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/14.diff">https://git.openjdk.org/jdk21u/pull/14.diff</a>

</details>

### CODE REVIEW

**Comment by theaoqi** [comment]
Hi @robm-openjdk, will the tags in jdk21 be merged to jdk21u? For example, jdk21 has
`jdk-21+28`, but not in jdk21u. Thanks.

**Comment by robm-openjdk** [comment]
This should be fixed. Skara has been configured to mirror jdk21 tags to jdk21u.

**Comment by theaoqi** [comment]
I have seen the tags. Thanks, @robm-openjdk.

**Pull request closed without merging**
