### PR TITLE
8311630: [s390] Implementation of Foreign Function & Memory API (Preview)

### PR DESCRIPTION
**Pull request by sid8606**
Hi all,

This pull request contains a backport of commit [ec1f7a84](https://github.com/openjdk/jdk/commit/ec1f7a8480db025a6f405817a106af8e92b69c44) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Sidraya on 21 Aug 2023 and was reviewed by Amit Kumar, Jorn Vernee and Martin Doerr.

This PR apply clean on jdk21u, testes with release, fastdebug and slowdebug build.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8311630](https://bugs.openjdk.org/browse/JDK-8311630) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8311630](https://bugs.openjdk.org/browse/JDK-8311630): [s390] Implementation of Foreign Function &amp; Memory API (Preview) (**Enhancement** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u.git pull/110/head:pull/110` \
`$ git checkout pull/110`

Update a local copy of the PR: \
`$ git checkout pull/110` \
`$ git pull https://git.openjdk.org/jdk21u.git pull/110/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 110`

View PR using the GUI difftool: \
`$ git pr show -t 110`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u/pull/110.diff">https://git.openjdk.org/jdk21u/pull/110.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u/pull/110#issuecomment-1695586830)

### CODE REVIEW

**Comment by sid8606** [comment]
\issue add 8314631

**Comment by TheRealMDoerr** [comment]
Ok, GHA Pre-submit test failure is unrelated.
/sponsor

**Pull request closed without merging**
